### PR TITLE
Update backmapping.py

### PR DESCRIPTION
**Pull request by ninadresing**
provide frames.HeliographicCarrington with an observer which is now obligatory

### CODE REVIEW

**Comment by johan12345** [comment]
I hope you tested that it works correctly like this? I was expecting it to be something like `observer='Earth'`, not `'Sun'` (because the observer distance from the Sun defines the duration of a Carrington rotation).

**Comment by ninadresing** [comment]
Hi Johan, 

Danke! Und ja gute Frage, welcher observer da besser ist. Ich hatte gedacht, es macht Sinn, wenn es immer auf die Sonne bezogen bleibt, da wir ja im sonnen-festen Carrington-Koordinatensystem arbeiten. Ich hatte es schnell verglichen und scheint auf den ersten Blick keinen Unterschied zu machen.
Ich hoffe, ich verstehe das gerade nicht falsch.

Gruß, 
Nina

**Comment by johan12345** [comment]
Ah:

> This system differs from Stonyhurst Heliographic (HGS) in its definition of longitude. This longitude is an “apparent” longitude because it takes into account the time it takes for light to travel from the Sun’s surface to the observer. Thus, the observer needs to be specified to be able to transform to any other coordinate frame.

([source](https://docs.sunpy.org/en/stable/api/sunpy.coordinates.frames.HeliographicCarrington.html#sunpy.coordinates.frames.HeliographicCarrington))

So the observer needs to be specified for speed-of-light correction (i.e. the difference should be very small, on the order of the rotation angle of the Sun within 8 minutes).

**Comment by ninadresing** [comment]
Right. And because we want the the positions of the spacecraft at the same time in the Carrington Frame I understand that the same observer hast to be used for all. It would probably also work for observer='Earth'.

**Comment by johan12345** [comment]
Yeah, it is probably fine like this. I'll go ahead and merge.

**Pull request merged**
